# Site Settings
title: Koustubh Gaikwad Resume
url: 'http://webjeda.com'
baseurl: '/resume' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Koustubh
tagline: Full Stack Web Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A full-time passionate Web Engineer with in excess of five years of experience in the IT industry in three different countries viz. India, USA and Japan in Research, B2B E-commerce and ERP domain. </br>
<p> I am currently employed as an Expert Software Engineer in a top ERP company in Tokyo, Japan where I do Full Stack Web Development. It also includes administration of Linux server infrastructure for the team.
<p> Previously, I have worked on projects involving benchmarking of cloud services for video encoding purposes and also on administering and maintaining server infrastructure for Video Streaming Services.'

#sidebar links
email: koustubh_gaikwad@yahoo.com
phone: +81-50-5539-2199
website: koustubh25.github.io/home #do not add http://
linkedin: koustubhg
github: koustubh25
twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
